<?php
declare(strict_types=1);

// JmespathFree SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

JmespathFreeUtility::setRegistrar(function (JmespathFreeUtility $u): void {
    $u->clean = [JmespathFreeClean::class, 'call'];
    $u->done = [JmespathFreeDone::class, 'call'];
    $u->make_error = [JmespathFreeMakeError::class, 'call'];
    $u->feature_add = [JmespathFreeFeatureAdd::class, 'call'];
    $u->feature_hook = [JmespathFreeFeatureHook::class, 'call'];
    $u->feature_init = [JmespathFreeFeatureInit::class, 'call'];
    $u->fetcher = [JmespathFreeFetcher::class, 'call'];
    $u->make_fetch_def = [JmespathFreeMakeFetchDef::class, 'call'];
    $u->make_context = [JmespathFreeMakeContext::class, 'call'];
    $u->make_options = [JmespathFreeMakeOptions::class, 'call'];
    $u->make_request = [JmespathFreeMakeRequest::class, 'call'];
    $u->make_response = [JmespathFreeMakeResponse::class, 'call'];
    $u->make_result = [JmespathFreeMakeResult::class, 'call'];
    $u->make_point = [JmespathFreeMakePoint::class, 'call'];
    $u->make_spec = [JmespathFreeMakeSpec::class, 'call'];
    $u->make_url = [JmespathFreeMakeUrl::class, 'call'];
    $u->param = [JmespathFreeParam::class, 'call'];
    $u->prepare_auth = [JmespathFreePrepareAuth::class, 'call'];
    $u->prepare_body = [JmespathFreePrepareBody::class, 'call'];
    $u->prepare_headers = [JmespathFreePrepareHeaders::class, 'call'];
    $u->prepare_method = [JmespathFreePrepareMethod::class, 'call'];
    $u->prepare_params = [JmespathFreePrepareParams::class, 'call'];
    $u->prepare_path = [JmespathFreePreparePath::class, 'call'];
    $u->prepare_query = [JmespathFreePrepareQuery::class, 'call'];
    $u->graphql_body = [JmespathFreeGraphql::class, 'body'];
    $u->graphql_errors = [JmespathFreeGraphql::class, 'errors'];
    $u->result_basic = [JmespathFreeResultBasic::class, 'call'];
    $u->result_body = [JmespathFreeResultBody::class, 'call'];
    $u->result_headers = [JmespathFreeResultHeaders::class, 'call'];
    $u->transform_request = [JmespathFreeTransformRequest::class, 'call'];
    $u->transform_response = [JmespathFreeTransformResponse::class, 'call'];
});
